### ISSUE TITLE
New import not working on English locale.

### ISSUE THREAD

**Issue by miurahr** [miurahr/tmpotter#56]
On Windows 7, click New button then happen next error with v0.8.5

```

[AWT-EventQueue-0] INFO org.tmpotter.ui.EditToolBar - Error execute method
java.lang.reflect.InvocationTargetException
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
         at java.lang.reflect.Method.invoke(Unknown Source)
         at 
org.tmpotter.ui.EditToolBar.actionPerformed(EditToolBar.java:108)
         at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
         at javax.swing.AbstractButton$Handler.actionPerformed(Unknown 
Source)
         at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown 
Source)
         at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
         at 
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
         at java.awt.Component.processMouseEvent(Unknown Source)
         at javax.swing.JComponent.processMouseEvent(Unknown Source)
         at java.awt.Component.processEvent(Unknown Source)
         at java.awt.Container.processEvent(Unknown Source)
         at java.awt.Component.dispatchEventImpl(Unknown Source)
         at java.awt.Container.dispatchEventImpl(Unknown Source)
         at java.awt.Component.dispatchEvent(Unknown Source)
         at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown 
Source)
         at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
         at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
         at java.awt.Container.dispatchEventImpl(Unknown Source)
         at java.awt.Window.dispatchEventImpl(Unknown Source)
         at java.awt.Component.dispatchEvent(Unknown Source)
         at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
         at java.awt.EventQueue.access$500(Unknown Source)
         at java.awt.EventQueue$3.run(Unknown Source)
         at java.awt.EventQueue$3.run(Unknown Source)
         at java.security.AccessController.doPrivileged(Native Method)
         at 
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown 
Source)
         at 
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown 
Source)
         at java.awt.EventQueue$4.run(Unknown Source)
         at java.awt.EventQueue$4.run(Unknown Source)
         at java.security.AccessController.doPrivileged(Native Method)
         at 
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown 
Source)
         at java.awt.EventQueue.dispatchEvent(Unknown Source)
         at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown 
Source)
         at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
         at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown 
Source)
         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
         at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.util.MissingResourceException: Can't find resource for 
bundle java.util.PropertyResourceBundle, key LBL.ENCODING.TOOLTIP
         at java.util.ResourceBundle.getObject(Unknown Source)
         at java.util.ResourceBundle.getString(Unknown Source)
         at 
org.tmpotter.filters.bitext.ImportWizardBiTextFile.initComponents(ImportWizardBiTextFile.java:369)
         at 
org.tmpotter.filters.bitext.ImportWizardBiTextFile.init(ImportWizardBiTextFile.java:73)
         at 
org.tmpotter.ui.wizard.ImportWizardController.registerPanels(ImportWizardController.java:51)
         at 
org.tmpotter.ui.wizard.ImportWizardController.<init>(ImportWizardController.java:43)
         at org.tmpotter.ui.wizard.ImportWizard.<init>(ImportWizard.java:53)
         at 
org.tmpotter.ui.ActionHandler.onNewImport(ActionHandler.java:529)
         at 
org.tmpotter.ui.ActionHandler.buttonNewActionPerformed(ActionHandler.java:632)
         ... 41 more
Exception in thread "AWT-EventQueue-0" 
java.lang.IncompatibleClassChangeError: Error invoke method handler for 
main menu
         at 
org.tmpotter.ui.EditToolBar.actionPerformed(EditToolBar.java:114)
         at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
         at javax.swing.AbstractButton$Handler.actionPerformed(Unknown 
Source)
         at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown 
Source)
         at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
         at 
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
         at java.awt.Component.processMouseEvent(Unknown Source)
         at javax.swing.JComponent.processMouseEvent(Unknown Source)
         at java.awt.Component.processEvent(Unknown Source)
         at java.awt.Container.processEvent(Unknown Source)
         at java.awt.Component.dispatchEventImpl(Unknown Source)
         at java.awt.Container.dispatchEventImpl(Unknown Source)
         at java.awt.Component.dispatchEvent(Unknown Source)
         at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown 
Source)
         at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
         at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
         at java.awt.Container.dispatchEventImpl(Unknown Source)
         at java.awt.Window.dispatchEventImpl(Unknown Source)
         at java.awt.Component.dispatchEvent(Unknown Source)
         at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
         at java.awt.EventQueue.access$500(Unknown Source)
         at java.awt.EventQueue$3.run(Unknown Source)
         at java.awt.EventQueue$3.run(Unknown Source)
         at java.security.AccessController.doPrivileged(Native Method)
         at 
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown 
Source)
         at 
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown 
Source)
         at java.awt.EventQueue$4.run(Unknown Source)
         at java.awt.EventQueue$4.run(Unknown Source)
         at java.security.AccessController.doPrivileged(Native Method)
         at 
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown 
Source)
         at java.awt.EventQueue.dispatchEvent(Unknown Source)
         at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown 
Source)
         at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
         at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown 
Source)
         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
         at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by miurahr** [comment]
It seems that some resource bundle key cannot be found then error was happened.
```
Caused by: java.util.MissingResourceException: Can't find resource for 
bundle java.util.PropertyResourceBundle, key LBL.ENCODING.TOOLTIP
```

**Comment by miurahr** [comment]
Actually Bundle.properties don't have it, but others have.
```
$ grep LBL.ENCODING.TOOLTIP src/main/resources/org/tmpotter/Bundle*properteis
Bundle_ca.properties:LBL.ENCODING.TOOLTIP=Seleccioneu la codificació de cada fitxer
Bundle_es.properties:LBL.ENCODING.TOOLTIP=Selecciona la codificaci\u00f3n de cada fichero.
Bundle_fr.properties:LBL.ENCODING.TOOLTIP=Sélectionnez l'encodage de chaque fichier
Bundle_ja_JP.properties:LBL.ENCODING.TOOLTIP=各ファイルのエンコーディングを選択
```

It may be happened on EN system locale. I can reproduce it by `env LANG=C tmpotter`
